import { APP_DESCRIPTION, APP_NAME, APP_OG_IMAGE_URL, APP_URL } from '@/lib/constants'
import { getMiniAppEmbedMetadata } from '@/lib/utils'
import type { Metadata } from 'next'
import { headers } from 'next/headers'

export const dynamic = 'force-dynamic'
export const revalidate = 0

// This is an example of how to generate a dynamically generated share page based on fid:
// Sharing this route e.g. exmaple.com/share/123 will generate a share page for fid 123,
// with the image dynamically generated by the opengraph-image API route.
export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ fid: string }>
  searchParams?: Promise<{ [key: string]: string | string[] | undefined }>
}): Promise<Metadata> {
  const resolvedParams = await params
  const resolvedSearchParams = searchParams ? await searchParams : undefined
  const { fid } = resolvedParams
  const fidNumber = Number(fid)
  const hasValidFid = Boolean(fidNumber && !Number.isNaN(fidNumber))
  const headerList = await headers()
  const host = headerList.get('x-forwarded-host') ?? headerList.get('host')
  const proto = headerList.get('x-forwarded-proto') ?? 'https'
  const baseUrl = host ? `${proto}://${host}` : APP_URL
  const shareImageParam =
    typeof resolvedSearchParams?.share_image_url === 'string'
      ? resolvedSearchParams.share_image_url
      : Array.isArray(resolvedSearchParams?.share_image_url)
        ? resolvedSearchParams?.share_image_url[0]
        : undefined
  const shareImageUrl =
    shareImageParam && shareImageParam.startsWith('http')
      ? shareImageParam
      : null
  const imageUrl =
    shareImageUrl ||
    (hasValidFid ? `${baseUrl}/api/og/humanid?fid=${fid}` : APP_OG_IMAGE_URL)

  return {
    title: `${APP_NAME} - Share`,
    openGraph: {
      title: APP_NAME,
      description: APP_DESCRIPTION,
      images: [{ url: imageUrl, width: 600, height: 400 }],
    },
    twitter: {
      card: 'summary_large_image',
      title: APP_NAME,
      description: APP_DESCRIPTION,
      images: [imageUrl],
    },
    other: {
      'fc:frame': JSON.stringify(
        getMiniAppEmbedMetadata(imageUrl || APP_OG_IMAGE_URL),
      ),
    },
  }
}

export default function SharePage() {
  return (
    <main className="min-h-screen bg-background text-primary flex items-center justify-center p-6">
      <div className="text-center space-y-2">
        <p className="text-lg">HUMAN ID CARD</p>
        <p className="text-xs text-secondary">
          Open this link inside the app to mint.
        </p>
      </div>
    </main>
  )
}
